///ts:export=mat2
import mat2_file = require('./mat2'); ///ts:export:generated
export var mat2 = mat2_file; ///ts:export:generated
///ts:export=mat2d
import mat2d_file = require('./mat2d'); ///ts:export:generated
export var mat2d = mat2d_file; ///ts:export:generated
///ts:export=mat3
import mat3_file = require('./mat3'); ///ts:export:generated
export var mat3 = mat3_file; ///ts:export:generated
///ts:export=mat4
import mat4_file = require('./mat4'); ///ts:export:generated
export var mat4 = mat4_file; ///ts:export:generated
///ts:export=quat
import quat_file = require('./quat'); ///ts:export:generated
export var quat = quat_file; ///ts:export:generated
///ts:export=vec2
import vec2_file = require('./vec2'); ///ts:export:generated
export var vec2 = vec2_file; ///ts:export:generated
///ts:export=vec3
import vec3_file = require('./vec3'); ///ts:export:generated
export var vec3 = vec3_file; ///ts:export:generated
///ts:export=vec4
import vec4_file = require('./vec4'); ///ts:export:generated
export var vec4 = vec4_file; ///ts:export:generated
