///ts:export=glContext,GL
import GL_file = require('./glContext'); ///ts:export:generated
export var GL = GL_file; ///ts:export:generated
///ts:export=shaders
import shaders_file = require('./shaders'); ///ts:export:generated
export var shaders = shaders_file; ///ts:export:generated
///ts:export=render
import render_file = require('./render'); ///ts:export:generated
export var render = render_file; ///ts:export:generated
///ts:export=camera
import camera_file = require('./camera'); ///ts:export:generated
export var camera = camera_file; ///ts:export:generated
///ts:export=texture
import texture_file = require('./texture'); ///ts:export:generated
export var texture = texture_file; ///ts:export:generated
///ts:export=renderObject
import renderObject_file = require('./renderObject'); ///ts:export:generated
export var renderObject = renderObject_file; ///ts:export:generated